var target = getHostname()

while (true) {
  secLev = getServerSecurityLevel(target);
  servMoNow = getServerMoneyAvailable(target);
  servMoMax = getServerMaxMoney(target)
  print("Security Level: " + secLev);
  print("Server Money: " + servMoNow);
  while (secLev > 1.200) {
    weaken(target);
    secLev = getServerSecurityLevel(target);
  }
  if (servMoNow < (servMoMax * 0.75)) {
    grow(target)
  }
  hack(target);
}